[workspace]
members = [
    ".",
    "tmpls",
    "tmpls/askama",
    "tmpls/horrorshow",
    "tmpls/markup",
    "tmpls/minijinja",
    "tmpls/rinja",
    "tmpls/tera",
    "tmpls/tinytemplate",
]
resolver = "2"

[package]
name = "template-benchmark"
version = "0.1.0"
edition = "2021"
publish = false
license = "Apache-2.0"

[features]
default = ["askama", "horrorshow", "markup", "minijinja", "rinja", "tera", "tinytemplate"]
askama = ["dep:askama"]
horrorshow = ["dep:horrorshow"]
markup = ["dep:markup"]
minijinja = ["dep:minijinja"]
rinja = ["dep:rinja"]
tera = ["dep:tera"]
tinytemplate = ["dep:tinytemplate"]

[dependencies]
tmpls = { version = "*", path = "tmpls" }

askama = { version = "*", optional = true, path = "tmpls/askama", package = "tmpl-askama" }
horrorshow = { version = "*", optional = true, path = "tmpls/horrorshow", package = "tmpl-horrorshow" }
markup = { version = "*", optional = true, path = "tmpls/markup", package = "tmpl-markup" }
minijinja = { version = "*", optional = true, path = "tmpls/minijinja", package = "tmpl-minijinja" }
rinja = { version = "*", optional = true, path = "tmpls/rinja", package = "tmpl-rinja" }
tera = { version = "*", optional = true, path = "tmpls/tera", package = "tmpl-tera" }
tinytemplate = { version = "*", optional = true, path = "tmpls/tinytemplate", package = "tmpl-tinytemplate" }

ahash = { version = "0.8.11", features = ["no-rng"] }
criterion = { version = "0.5.1", features = ["html_reports"] }
quanta = "0.12.3"

[[bench]]
name = "template-benchmark"
harness = false
