[package]
name = "tmpl-rinja"
version = "0.1.0"
edition = "2021"
publish = false
license = "Apache-2.0"

[dependencies]
tmpls = { version = "*", path = ".." }

rinja = { version = "0.3.0", git = "https://github.com/rinja-rs/rinja", branch = "master" }
